CREATE DATABASE TodoDB;

USE TodoDB;

CREATE TABLE IF NOT EXISTS Users (
	RegNo INT AUTO_INCREMENT PRIMARY KEY,
  	FirstName VARCHAR(50),
  	LastName VARCHAR(50),
  	Username VARCHAR(50) NOT NULL,
  	Email VARCHAR(150) NOT NULL,
  	Password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Todo (
	ID INT AUTO_INCREMENT PRIMARY KEY,
  	User INT,
  	Name VARCHAR(50) NOT NULL,
  	Description TEXT,
    Status BOOL DEFAULT FALSE,
	FOREIGN KEY (User) REFERENCES Users(RegNo)
);